use crate::object::Object;

#[derive(Debug, PartialEq, Eq, Clone, Copy, PartialOrd, Ord)]
pub enum TokenType
{
    // Single char tokens
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    Comma,
    Dot,
    /// Subtraction
    Minus,
    /// Addition
    Plus,
    Semicolon,
    /// Division
    Slash,
    /// Multiplication
    Star,

    // One or two char tokens
    Bang,
    BangEqual,
    Assign, // Assignment
    Equal,  // Equality
    Greater,
    GreaterEqual,
    Less,
    LessEqual,

    // Literals
    Identifier,
    /// String literal
    String,
    /// Number literal
    Number,

    // Keywords
    And,
    Class,
    Else,
    False,
    Fun,
    If,
    Nil,
    Or,
    Print,
    Return,
    Super,
    This,
    True,
    /// Variable declaration
    Var,

    While,
    For,
    Break,

    /// End of file
    Eof,
}

#[derive(Debug, PartialEq, Clone)]
/// A token to be generated by the lexer
pub struct Token
{
    /// The type of the token
    ttype: TokenType,
    pub lexeme: String,
    pub literal: Option<Object>,

    /// The line the token was found on
    pub line: usize,
}

impl Token
{
    pub fn get_identifier(&self) -> String { self.lexeme.to_string() }

    /// Create a new `Token`
    pub fn new(ttype: TokenType, lexeme: String, literal: Option<Object>, line: usize) -> Self
    {
        Self {
            ttype,
            lexeme,
            literal,
            line,
        }
    }

    /// Check if a `Token` is of a specific `TokenType`
    pub fn is(&self, ttype: TokenType) -> bool { self.ttype == ttype }

    /// Create an EOF token
    pub fn eof(line: usize) -> Token
    {
        Token {
            ttype: TokenType::Eof,
            lexeme: "".to_string(),
            literal: None,
            line,
        }
    }

    pub fn token_type(&self) -> TokenType { self.ttype }
}

impl std::fmt::Display for Token
{
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result
    {
        write!(
            f,
            "{:?} {} {}",
            self.ttype,
            self.lexeme,
            if let Some(literal) = &self.literal
            {
                literal.to_string()
            }
            else
            {
                "None".to_string()
            }
        )
    }
}
